//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{    
    public class ChiTietHoaDonXuat
    {
        public int MaChiTietHoaDonXuat { get; set; }
        public int MaHoaDonXuat { get; set; }
        public int MaSanPham { get; set; }
        public int SoLuong { get; set; }
        public double GiaBan { get; set; }
        public double ChietKhau { get; set; }
        public int TraLai { get; set; }

    }
}
