//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Models
{

    
    public partial class KiemKho
    {
 
    
        public int MaKiemKho { get; set; }
        public int MaNhanVien { get; set; }
        public DateTime ThoiGianBatDau { get; set; }
        public DateTime ThoiGianKetThuc { get; set; }
        public bool TrangThaiKho { get; set; }
        public int MaKho { get; set; }
        public string MoTa { get; set; }
        public List<ChiTietKiemKho> listjson_chitietkiemkho { get; set; }

    }
}
