//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Models
{
    public partial class SanPham
    {
        public int MaSanPham { get; set; }
        public int MaLoai { get; set; }
        public string TenSanPham { get; set; }
        public string MoTaSanPham { get; set; }
        public string AnhDaiDien { get; set; }
        public int MaNSX { get; set; }
        public int MaDonViTinh { get; set; }
        public double GiaBan { get; set; }
        public double GiaGiam { get; set; } 
        public DateTime NgayTao { get; set; }
        public DateTime NgaySua { get; set; }
        public List<ChiTietAnh> listjson_chitietanh { get; set; }
        public List<ThongSoKyThuat> listjson_thongsokythuat { get; set; }

    }
}
