//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Models
{ 
    public partial class Slide
    {
        public int MaSlide { get; set; }
        public string Anh { get; set; }
        public string Link { get; set; }
        public DateTime NgayTao { get; set; }
    }
}
