//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Models
{
    public partial class TinTuc
    {
        public int MaTinTuc { get; set; }
        public int MaNhanVien { get; set; }
        public string TieuDe { get; set; }
        public string TomTat { get; set; }
        public string Anh { get; set; }
        public DateTime NgayTao { get; set; }
        public List<ChiTietTinTuc> listjson_chitiettintuc { get; set; }

    }
}
