//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    public class ChiTietAnh
    {
        public int MaAnhChiTiet { get; set; }
        public int MaSanPham { get; set; }
        public string Anh { get; set; }

    }
}
