//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Models
{
    public partial class ThongSoKyThuat
    {
        public int MaThongSo { get; set; }
        public int MaSanPham { get; set; }
        public string TenThongSo { get; set; }
        public string MoTa { get; set; }

    }
}
